#!/bin/bash

set -e

clone_repository() {
	rm -rf ${ROOT_DIR}/odp
	pushd ${ROOT_DIR}
	PKG_URL=${PKG_URL:-git://git.linaro.org/lng/odp-dpdk.git}
	PKG_BRANCH=${PKG_BRANCH:-master}
	PKG_DIR=${PKG_DIR:-${ROOT_DIR}/odp}
	git clone -b ${PKG_BRANCH} ${PKG_URL} ${PKG_DIR}
	popd
}

prepare_tarball() {
	export package=opendataplane

	pushd ${PKG_DIR}

	if [[ -d ${PKG_DIR}/.git ]]; then
		. scripts/git_hash.sh ${PKG_DIR}
		version=$(cat .scmversion)
	else
		echo "This script isn't expected to be used without"
		echo "a git repository."
		exit 1
	fi

	if [ "$1" == archive ]; then
		git archive --format=tar --prefix=${package}-${version}/ HEAD > ${package}-${version}.tar

		# append .scmversion, otherwise bootstrap fails
		SCMTMP=`mktemp -d`
		pushd $SCMTMP
		mkdir ${package}-${version}
		cp ${PKG_DIR}/.scmversion ${package}-${version}
		tar --update -v -f ${PKG_DIR}/${package}-${version}.tar ${package}-${version}
		popd
		rm -rf $SCMTMP
		gzip ${package}-${version}.tar
	else
		./bootstrap
		./configure
		make dist
	fi

	popd
	cp ${PKG_DIR}/${package}-${version}.tar.gz ${ROOT_DIR}/${package}-${version}.tar.gz
}
