#!/bin/bash

set -e

clone_repository() {
	rm -rf ${ROOT_DIR}/odp
	pushd ${ROOT_DIR}
	PKG_URL=${PKG_URL:-git://git.linaro.org/lng/odp.git}
	PKG_BRANCH=${PKG_BRANCH:-master}
	git clone -b ${PKG_BRANCH} ${PKG_URL}
	popd
}

prepare_tarball() {
	export package=opendataplane

	pushd ${ROOT_DIR}
	pushd ${ROOT_DIR}/odp

	if [[ -d ${ROOT_DIR}/odp/.git ]]; then
		. scripts/git_hash.sh ${ROOT_DIR}/odp
		version=$(cat .scmversion)
	else
		echo "This script isn't expected to be used without"
		echo "a git repository."
		exit 1
	fi

	if [ "$1" == archive ]; then
		git archive --format=tar --prefix=${package}-${version}/ HEAD > ${package}-${version}.tar

		# append .scmversion, otherwise bootstrap fails
		SCMTMP=`mktemp -d`
		pushd $SCMTMP
		mkdir ${package}-${version}
		cp ${ROOT_DIR}/odp/.scmversion ${package}-${version}
		tar --update -v -f ${ROOT_DIR}/odp/${package}-${version}.tar ${package}-${version}
		popd
		rm -rf $SCMTMP
		gzip ${package}-${version}.tar
	else
		./bootstrap
		./configure
		make dist
	fi

	popd
	cp ${ROOT_DIR}/odp/${package}-${version}.tar.gz ${package}_${version}.orig.tar.gz
	tar xzf ${package}_${version}.orig.tar.gz
}
